name: tests

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - php: '8.2'
            dependencies: lowest
            composer-options: --prefer-lowest --prefer-stable
          - php: '8.2'
            dependencies: stable
            composer-options: --prefer-stable
          - php: '8.3'
            dependencies: stable
            composer-options: --prefer-stable
          - php: '8.4'
            dependencies: stable
            composer-options: --prefer-stable

    name: PHP ${{ matrix.php }} / ${{ matrix.dependencies }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          tools: composer:v2

      - name: Cache Composer packages
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache/files
          key: ${{ runner.os }}-php-${{ matrix.php }}-${{ matrix.dependencies }}-composer-${{ hashFiles('composer.json') }}
          restore-keys: |
            ${{ runner.os }}-php-${{ matrix.php }}-${{ matrix.dependencies }}-composer-
            ${{ runner.os }}-php-${{ matrix.php }}-composer-

      - name: Validate Composer
        run: composer validate --strict

      - name: Install Dependencies
        run: composer update ${{ matrix.composer-options }} --prefer-dist --no-interaction --no-progress

      - name: Run Pint
        run: composer format:test

      - name: Run Static Analysis
        run: composer analyse

      - name: Run Tests
        run: composer test

      - name: Run Release Audit
        run: composer audit:release
